(def fib (lambda (n)
           (def l '())
           (def a 0)
           (def b 1)
           (def i 0)
           (while (< i n)
                  (def temp b)
                  (def b (+ a b))
                  (def a b)
                  (push! l a)
                  (def i (+ 1 i)))
           l))

(print (fib 75))
